<a href="https://colab.research.google.com/github/Shanu-Mathew/Tensorflow-Notes/blob/main/Tensorflow_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow Notes


In [ ]:
#Importing Tensorflow
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.12.0


In [ ]:
#Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimension of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Creatre a matrix (has more than 1 dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
#This is done since storing this in 16 bit precision takes less space in memory
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Creating a tensor
tensor=tf.constant([[[1,2,3],
                      [4,5,6]],
                    [[7,8,9],
                      [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Definition of Terms:

* scalar: A single number
* vector: A number with direction (e.g. wind speed and direction)
* matrix: A 2-Dimensional array of numbers
* tensor: A n-Dimensional array of numbers (where n can be any number, a 0-D is a scalar, 1-D is vector)

## Creating tensors with tf.variable

In [ ]:
changeable_tensor=tf.Variable([10,7])

In [ ]:
unchangeable_tensor=tf.constant([10,7])

In [ ]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

NameError: ignored

##### Note:- Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as Tensorflow does this for you

### Creating Random Tensors

In [ ]:
random_1= tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2=tf.random.Generator.from_seed(78)
random_2=random_2.normal(shape=(3,2))

In [ ]:
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.4084325 , -1.8613014 ],
        [ 1.0928144 , -0.29996362],
        [-0.7382552 ,  1.2053189 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of elements in a Tensor

In [ ]:
#Shuffle a tensor (valuable for when you want to shuffle your data so that the inherent order doesnt't effect learning)
not_shuffled=tf.constant([[10,7],
                         [3,4],
                         [2,5]])
shuffled=tf.random.shuffle(value=not_shuffled, seed=42)
tf.random.set_seed(42)
not_shuffled,shuffled

### Other ways to make Tensors

In [ ]:
#Create a tensor for all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor for all zeros
tf.zeros([10,8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Creating tensors using numpy

In [ ]:
numpy_A=np.arange(1,25,dtype=np.int32)
X=tf.constant(numpy_A,shape=(2,3,4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors
* Shape
* Rank
* Axis or Dimension
* Size


In [ ]:
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#shape
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
#Rank
rank_4_tensor.ndim

4

In [ ]:
#Size
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
#Get various attributes of the tensor

#type
type_tf=rank_4_tensor.dtype

#Number of elements in 0th axis
ele_0_axis=rank_4_tensor.shape[0]

#Number of elements in last axis
ele_last_axis=rank_4_tensor.shape[-1]
type_tf,ele_0_axis,ele_last_axis

(tf.float32, 2, 5)

### Indexing Tensors
Tensors can be indexed just like python lists

In [ ]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
#Slicing for first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
 #Get the first element from each dimension from each index except for the final one
 rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to Newaxis
tf.expand_dims(rank_2_tensor,axis=-1) #"-1" means expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors
**Basic Operators**


In [ ]:
#Addition
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Multiplication
tensor*10,tf.multiply(tensor,10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>)

In [ ]:
#Subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

### Matrix Multiplications

In [ ]:
#Matrix Multiplication
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
one_m=tf.constant(np.array([1,2,5,7,2,1,3,3,3],dtype=np.int32),shape=(3,3))
two_m=tf.constant(np.array([3,5,6,7,1,8],dtype=np.int32),shape=(3,2))
one_m,two_m

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
tf.matmul(one_m,two_m)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#Matrix multiplication with python operator "@"
one_m @ two_m

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#Transpose
one_m, tf.transpose(one_m)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 7, 3],
        [2, 2, 3],
        [5, 1, 3]], dtype=int32)>)

In [ ]:
#Matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(one_m),one_m)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[59, 25, 21],
       [25, 17, 21],
       [21, 21, 35]], dtype=int32)>

#### Dot Product
Matrix multiplication is also referred to as the dot product.
You can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()

In [ ]:
# Perform the dot product on X and Y
tf.tensordot(one_m,two_m,axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

### Changing the datatype of the tensors

In [ ]:
#Creating tensor with default datatype (float32)
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
# Change from float32 to float16 (reduced precision)
B=tf.cast(B,dtype=tf.float16)
B.dtype

tf.float16

In [ ]:
# Int32 to float32
C=tf.constant([1,2,3,4])
C=tf.cast(C,dtype=tf.float32)
C.dtype

tf.float32

### Tensorflow Aggregation

In [ ]:
#Get the absolute values
B=tf.constant([-7,-10])
tf.abs(B)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Minimum Value in a tensor
tf.reduce_min(B)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [ ]:
# Maxmimum Value in a tensor
tf.reduce_max(B)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [ ]:
#Find the mean
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [ ]:
# Find the sum
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [ ]:
#Variance
import tensorflow_probability as tfp
tfp.stats.variance(B), tf.math.reduce_variance(tf.cast(B,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.25>)

In [ ]:
#Standard Deviation
tf.math.reduce_std(tf.cast(B,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

In [ ]:
### Positional Maximum and Minimum
B=tf.random.uniform(shape=[50])
B

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.57349086, 0.04711831, 0.67997944, 0.87732136, 0.8653556 ,
       0.32775438, 0.15285552, 0.9463471 , 0.6704961 , 0.42215347,
       0.05257177, 0.4548794 , 0.7246543 , 0.24128842, 0.08418512,
       0.83301485, 0.3677125 , 0.82953966, 0.21053016, 0.76545954,
       0.08354354, 0.03936374, 0.9804326 , 0.5089114 , 0.5484992 ,
       0.9232832 , 0.0383451 , 0.60781014, 0.53564954, 0.26932478,
       0.6127796 , 0.82882845, 0.11104226, 0.16583347, 0.31327605,
       0.73836076, 0.9894092 , 0.7793348 , 0.83360493, 0.7014024 ,
       0.52285373, 0.79536927, 0.57104504, 0.01812136, 0.14271724,
       0.27158642, 0.09841418, 0.01404393, 0.8808639 , 0.10007083],
      dtype=float32)>

In [ ]:
# Positional Maxima
tf.argmax(B)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [ ]:
#Index on our largest value position
B[tf.argmax(B)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9894092>

In [ ]:
#Max value of B
tf.reduce_max(B)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9894092>

In [ ]:
#Positional Minimum
tf.argmin(B),B[tf.argmin(B)]

(<tf.Tensor: shape=(), dtype=int64, numpy=47>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.014043927>)

### Squeezing a tensor (removing all single dimensions)


In [ ]:
#Create a tensor to get started
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.44169688, 0.67774427, 0.9106015 , 0.863088  , 0.65841556,
           0.4383111 , 0.02138019, 0.63682306, 0.8314185 , 0.937698  ,
           0.60821927, 0.1514442 , 0.02384353, 0.9054736 , 0.9553982 ,
           0.7356956 , 0.25789225, 0.5104078 , 0.8259711 , 0.16241801,
           0.22637522, 0.96359396, 0.9434515 , 0.3017311 , 0.7571187 ,
           0.95600903, 0.25171483, 0.6440718 , 0.9885378 , 0.13310266,
           0.10477412, 0.92806363, 0.07054853, 0.04710579, 0.468799  ,
           0.00108731, 0.31522143, 0.1147027 , 0.58829963, 0.10891414,
           0.54909945, 0.25307357, 0.8670211 , 0.62047493, 0.35263503,
           0.49828386, 0.12449169, 0.95389724, 0.61141586, 0.5443257 ]]]]],
      dtype=float32)>

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.44169688, 0.67774427, 0.9106015 , 0.863088  , 0.65841556,
        0.4383111 , 0.02138019, 0.63682306, 0.8314185 , 0.937698  ,
        0.60821927, 0.1514442 , 0.02384353, 0.9054736 , 0.9553982 ,
        0.7356956 , 0.25789225, 0.5104078 , 0.8259711 , 0.16241801,
        0.22637522, 0.96359396, 0.9434515 , 0.3017311 , 0.7571187 ,
        0.95600903, 0.25171483, 0.6440718 , 0.9885378 , 0.13310266,
        0.10477412, 0.92806363, 0.07054853, 0.04710579, 0.468799  ,
        0.00108731, 0.31522143, 0.1147027 , 0.58829963, 0.10891414,
        0.54909945, 0.25307357, 0.8670211 , 0.62047493, 0.35263503,
        0.49828386, 0.12449169, 0.95389724, 0.61141586, 0.5443257 ],
       dtype=float32)>,
 TensorShape([50]))

### One Hot Encoding

In [ ]:
some_list=[0,1,2,3]

#One hot encode the list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=4,on_value="Yo", off_value="Lo")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo', b'Lo', b'Lo', b'Lo'],
       [b'Lo', b'Yo', b'Lo', b'Lo'],
       [b'Lo', b'Lo', b'Yo', b'Lo'],
       [b'Lo', b'Lo', b'Lo', b'Yo']], dtype=object)>

### Mathematical Operations


In [ ]:
#Squaring
H=tf.range(1,10)
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Square Root (Method requires non int type)
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
Note:- Main difference is that a Tensor can run on a GPU or TPU for faster processing

In [ ]:
#Create a tensor directly from a numpy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert our tensor back to a Numpy array
np.array(J),J.numpy(),type(J.numpy()),type(J)

(array([ 3.,  7., 10.]),
 array([ 3.,  7., 10.]),
 numpy.ndarray,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
J.numpy()[0]

3.0

In [ ]:
#Default types of each are slightly different
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])

#check datatypes
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu Jun 15 12:22:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:-** If you have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible